# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test stop function
#'
#' Test stop function
#'
#' @export
dostop <- function() {
    .Call('_rcpptest_dostop', PACKAGE = 'rcpptest')
}

